title: ""
description: "Assistant Professor of Mathematics at The University of Alabama"
email: "ywang348@ua.edu"

url: "https://wongelle08.github.io"
baseurl: ""

theme: jekyll-theme-primer

author:
  name: "Yiran Wang"
